command:
  - python
  - finetune_on_fingerprints.py
  - --name=${envvar:SWEEP_MODEL_SIZE}-${envvar:SWEEP_DATASET}
  - --dataset=${envvar:SWEEP_DATASET}
  - --fingerprints-path=${envvar:SWEEP_FINGERPRINTS_PATH}
  - ${args}
entity: graphcore
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  epochs:
    values:
      - 20
  combine-input:
    values:
      - concat
      - none
  depth:
    values:
      - 3
      - 4
  dropout-rate:
    values:
      - 0
      - 0.1
  hidden-dim:
    values:
      - 512
      - 1024
      - 2048
  lr:
    values:
      - 0.00075
      - 0.0003
      - 0.0001
  warmup-epochs:
    values:
      - 0
      - 5
  lr-schedule:
    values:
      - constant
      - linear
      - cosine